### ISSUE TITLE
Add some kind of local cache for objects, libs and binaries

### ISSUE THREAD

**Issue by aschaal** [esrlabs/bake#107]
Maybe based on SHA-1 of preprocessor or SHA-1 of all dependent header files etc in combination with command line flags etc...
If equal, the compiler does not need to compile and so on...

**Comment by flxo** [comment]
Doing cache like things is a project on it's own. This topic can get quite complex and probably beyond the scope a build system. Currently two projects exists that implement this kind of caches: [ccache](https://ccache.samba.org/) and [sccache](https://ccache.samba.org/).

Bake should provide a easy way to integrate those extensions via something like

```
SetCompilerWrapper "sccache"
```

in the project configuration.

**Comment by flxo** [comment]
See #90.

**Comment by aschaal** [comment]
Fixed with 2.31.0, see "prefix" attribute of Compiler definition in (Default)Toolchain.
