### ISSUE TITLE
The prebuild feature should be supported on object file level

### ISSUE THREAD

**Issue by mthiede** [esrlabs/bake#112]
Maybe the user can choose to make a whole project/archive prebuild or single object files.

For reduing the number of changed binary files per build, one would always switch to object file mode. At least with Diab object files are the same when rebuilt with the same input whereas archives are not (e.g. they include the timestamp of the contained object files).

So there should be a feature for saying "all object files of project X should be prebuild".
As an add on there could be a feature for marking a particular subset of object files from a project as prebuild.

**Comment by aschaal** [comment]
Done in 2.24.0. If objects exist, they are used instead of the archive.
