### ISSUE TITLE
Remove documentation folder from rubygem

### ISSUE THREAD

**Issue by gizmomogwai** [esrlabs/bake#129]
The gem is really big (5mb) .. most of it is the html documentation.

**Comment by aschaal** [comment]
Some discussions were made already offline from github. Seems not everybody is happy with that change.
Current options:
1) leave it as it is
2) removing docu from gem and link to online docu (which is exactly the same)
3) dto + providing extra gem with docu
4) replacing docu with some kind of "quick start"

I would prefer 1) or 2).

What do you think?

**Comment by gizmomogwai** [comment]
@Nicoretti had mainly a problem with breaking existing workflows. we could introduce a core-gem without docs. the normally used bake-toolkit required this + brings the documentation. if someone really cares, he installs only bake-toolkit-core and if not he installs bake-toolkit as he is used to.

**Comment by aschaal** [comment]
Yes, maybe. So most probably the only thing I need is another gemspec...
bake-toolkit stays the same, and bake-toolkit-nodoc is the small version.

**Comment by aschaal** [comment]
I think different now. With a bake-toolkit-nodoc gem we would have the source code and the binaries twice, which  means you overwrite the stuff when installing both gems.

I will remove the docu from the bake-toolkit. But I add an option in bake, e.g. "bake --install-doc" which installs the docu for offline usage --> "bake --doc" points to online docu per default. If you have install the docu, the offline docu will be opened. 

Is that okay?

**Comment by gizmomogwai** [comment]
sure .. for me everything is ok ... i would not have done 2 gems carrying everything, the bake-toolkit-no-doc has the code, the bake-toolkit depends on this and only brings the docs ... but perhaps its indeed easier with the installable things.

only argument from @Nicoretti  against this would be, that usually you do not have the docs installed, and then you are offline, and exactly then you want to peek into the docs.

**Comment by aschaal** [comment]
I have added the "--install-doc" command.

@Nicoretti: for you it is now:
   gem install bake-toolkit
   bake --install-doc

I assume for almost everybody the online docu is suitable.
