### ISSUE TITLE
The --file-list option is broken with no build done before

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#131]
The `--file-list` option only works if a (successful) build happened before.

**Comment by aschaal** [comment]
Yes, this is intended. bake does not know the dependent header files. In combination with #130 I will add a better error message is workspace was not built before.

**Comment by flxo** [comment]
Why do you want to split the file list generation from the build? If a build really needs to be done then the option only make sense in combination with a build.

**Comment by aschaal** [comment]
Good point.

**Comment by flxo** [comment]
Solved with v2.29.2
