### ISSUE TITLE
cleanup bootstrap in generated html files

### ISSUE THREAD

**Issue by gizmomogwai** [esrlabs/bake#132]
afer running make in documentation i have this:

    ls -la documentation/_build/html/_static/ | grep boots
    drwxr-xr-x@  5 gizmo  staff     170 Jan 25 15:13 bootstrap-2.3.2
    drwxr-xr-x@  5 gizmo  staff     170 Jan 25 15:13 bootstrap-3.3.6
    -rw-r--r--@  1 gizmo  staff    3329 Jan 25 15:13 bootstrap-sphinx.css
    -rw-r--r--@  1 gizmo  staff    5066 Jan 25 15:13 bootstrap-sphinx.js
    drwxr-xr-x@ 16 gizmo  staff     544 Jan 25 15:13 bootswatch-2.3.2
    drwxr-xr-x@ 20 gizmo  staff     680 Jan 25 15:13 bootswatch-3.3.6

**Comment by aschaal** [comment]
Note, that I have already a script called fixBootstrap.sh which  has to be executed after "make html".

Nicoretti, do we need all these files mentioned by gizmomogwai?

**Comment by aschaal** [comment]
Deleted bootswatch-2.3.2 and bootstrap-2.3.2.
The rest is needed for the docu.
