### ISSUE TITLE
Project creation from template should not name a binary exe

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#134]
The option `exe` within `--create exe|lib|custom` is kind of Windows agnostic. I'd suggest to replace it with `bin` and slightly revise the help text to:

`--create bin|lib|custom  Creates a project from binary, library or custom template`

**Comment by aschaal** [comment]
I will not change that as long as the ExecutubleConfig is named EXEcutableConfig. This may be a refactoring for the future.
However, I have adapted the template, they are not closer to ESRLabs standard.
