### ISSUE TITLE
Support for whitespace in toolchain path

### ISSUE THREAD

**Issue by domzigm** [esrlabs/bake#143]
I'm using following configuration in my Project.meta

`Set GCCPATH, value: "C:/Program Files (x86)/Atmel/Studio/7.0/toolchain/arm/arm-gnu-toolchain/bin"`
some lines below...
`Compiler CPP, command: "$(GCCPATH)/arm-none-eabi-g++.exe"`

Bake will fail with following message:
> C:/Program Files (x86)/Atmel/Studio/7.0/toolchain/arm/arm-gnu-toolchain/bin/arm-none-eabi-gcc.exe ...
> No such file or directory - C:/Program
> C:/Users/my.name/Documents/Atmel Studio/7.0/ProjectFolder: Error: System command failed

When manually adding \" to the path:
> Invalid argument - "C:/Program Files (x86)/Atmel/Studio/7.0/toolchain/arm/arm-gnu-toolchain/bin/arm-none-eabi-gcc.exe"
> C:/Users/my.name/Documents/Atmel Studio/7.0/ProjectFolder: Error: System command failed

**Comment by aschaal** [comment]
Fixed in upcoming 2.38.0 release today afternoon.

You can use now quotes like this:
Compiler CPP, command: "\"$(GCCPATH)/arm-none-eabi-g++.exe\""
or
Compiler CPP, command: "'$(GCCPATH)/arm-none-eabi-g++.exe'"
