### ISSUE TITLE
'projDir' variable used but not declared

### ISSUE THREAD

**Issue by tfrimor** [esrlabs/bake#146]
The method "write_depfile" uses variable 'projDir' in the debug output if it cannot create the dependency file. 'projDir' isn't declared though.

I currently presume that is what giving me current error: 
"Error: undefined local variable or method `projDir' for Bake::Blocks::Compile:Class"

**Comment by tfrimor** [comment]
Added missing variable to write dependency function. It is tested and works as intended on the build server.

**Comment by aschaal** [comment]
Thx!!!
