### ISSUE TITLE
Add option to bakeqac to not filter for files

### ISSUE THREAD

**Issue by tea-age** [esrlabs/bake#150]
With bakeqac option  --qacnofilter the output will not be filtered at all.
Filtering is a two step process:
* Filtering for file folders
* Filtering for certain messages
It would be good to have an option to apply the message filters but
not apply the file folder filter

**Comment by aschaal** [comment]
Fixed in upcoming 2.38.0 release today afternoon.

You can use now
--qacnomsgfilter
--qacnofilefilter
