### ISSUE TITLE
Offer a way to auto-format the Project.meta files

### ISSUE THREAD

**Issue by elektronenhirn** [esrlabs/bake#156]
We have more and more Project.meta files where tabs and spaces are mixed and the Indentation style is varying.

**Comment by gizmomogwai** [comment]
what about https://github.com/esrlabs/bake/blob/master/bin/bake-format

**Comment by aschaal** [comment]
In future I would like to use the rtext gem, which can read and rewrite the Project.meta files. Imho this should not be too complicated.

This bake-format was a nice contribition to the bake toolkit. elektronenhirn, maybe this is already what you need.

**Comment by elektronenhirn** [comment]
Thanks, I was not aware of bake-format. Worked very well for me, thanks!
