### ISSUE TITLE
Specify adaptations by path instead of a directory search pattern 

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#160]
The way `bake` searches for adapts is a little bit awkward: Passing something like `--adapt debug` makes `bake` search for a directory called `debug` that contains a file named `Adapt.meta`. 

A more convenient way would be pass the *path* to a adaption file instead of a directory search pattern. e.g:

`bake --adapt build/debug_flags.bake --adapt build/toolchain-arm-linux-gnueabihf.bake`

This would allow to

1. use custom and descriptive names for the adaptations files instead of `Adapt.meta` (!)
2. allow the handling of multiple adaptations files with the same name in one project tree (useful for multiple targets: `bake --adapt build/$(TARGET)/toolchain.adapt`
3. make clear what happens instead of using some bake internal search magic.
4. allow multiple adaption files in one directory

**Comment by aschaal** [comment]
Agreed.
I will change that. If ABC in "--adapt ABC" is a valid file (relative to working dir or main dir) I will use it directly, otherwise I will fall back to current solution (ABC/Adapt.meta).

**Comment by aschaal** [comment]
Fixed with release 2.45.0.
