### ISSUE TITLE
CompilerPrefix should not be used for assembler calls

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#172]
The `CompilerPrefix` is applied (if not specified else) to calls to  the `C`, `C++` and `Assembler`. Since at least the `das` (Diab assembler) behaves totally different than 'dcc' or `dplusplus` a dedicated prefix setting for the assembler should be added: `AssemblerPrefix`. 

Currently a workaround is to declare the prefix with the toolchain definition for `C` and `CPP` and *not* `ASM`.

**Comment by aschaal** [comment]
Done. CPPCompilerPrefix, CCompilerPrefix and ASMCompilerPrefix now available. They have higher prio than CompilerPrefix, which is still available for backward compatibility.
