### ISSUE TITLE
Eclipse plugin installation problem (PKIX path validation failed)

### ISSUE THREAD

**Issue by mesaamesa** [esrlabs/bake#173]
Trying to install the plugin eclipse after https://esrlabs.github.io/bake/ide/eclipse/eclipse.html I have got the following error:
Unable to read repository at https://assets.esrlabs.com/eclipse-plugins/com.esrlabs.eclipse.bake.updatesite/content.xml.
Unable to read repository at https://assets.esrlabs.com/eclipse-plugins/com.esrlabs.eclipse.bake.updatesite/content.xml.
sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed

attached eclipse.ini and eclipse.cfg.
[eclipse.cfg.txt](https://github.com/esrlabs/bake/files/2366519/eclipse.cfg.txt)
[eclipse.ini.txt](https://github.com/esrlabs/bake/files/2366520/eclipse.ini.txt)

**Comment by Nicoretti** [comment]
@aschaal this might be still the issue of the update site being down isn't it?

**Comment by aschaal** [comment]
Works again. Problem was an outdated certificate on the webserver.
