### ISSUE TITLE
Bake should escape quotes in compile_commands export

### ISSUE THREAD

**Issue by resetnow** [esrlabs/bake#175]
In compile_commands.json, some macro definitions may contain quotes. They seem to be escaped when starting a process, but not in the compile_commands file.

Example (exported with CMake):

```
-DESTL_HARD_ASSERT_HEADER=\"ecu_assert.h\"
```

Same code exported with Bake:

```
-DESTL_HARD_ASSERT_HEADER="ecu_assert.h" 
```

The following command may be used to test contents of compile_commands.json:

```
jq -r '.[] .command' < compile_commands.json | grep -o "\-DESTL_HARD_ASSERT_HEADER=[^ ]*" | head -n1
```

**Comment by aschaal** [comment]
Fixed with 2.53.0
