### ISSUE TITLE
Case sensitivity issue when changing flags for specific files

### ISSUE THREAD

**Issue by ReneW10** [esrlabs/bake#177]
With bake v.2.19.1 there is an issue with the case sensitivity when changing compiler flags for files:

  Files "source/somepath/file.c" {
      Flags add: "--newFlag"
  }

will compile file.c, but will not add the "--newFlag" to the compiler call if file.c is in SOMEPATH instead of somepath.
This is confusing and leads to possibly compilation.
Either it should not compile with the info that file.c does not exist or the file should compile with the newFlag.

(not sure whether this is already fixed in a newer version)

**Comment by aschaal** [comment]
Thank you for the info, fixed in upcoming 2.54 release.
