### ISSUE TITLE
bake --create exe ----> Error: undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by robert-at-accenture** [esrlabs/bake#195]
When following the [bake Quickstart guide](https://esrlabs.github.io/bake/source/quickstart/quickstart.html) and executing `bake --create exe` the ``Error: undefined method `exists?' for File:Class`` error is thrown on **Windows 11 & ruby 3.2.0 (2022-12-25 revision a528908271) [x64-mingw-ucrt]**

**Comment by gizmomogwai** [comment]
Finally ruby removed the long deprecated `File.exists?` and `Dir.exists?` in comit `bf97415c02b11a8949f715431aca9eeb6311add2`.

This is included in all ruby 3.2.0 versions:
```
git tag --contains bf97415c02b11a8949f715431aca9eeb6311add2
v3_2_0
v3_2_0_preview1
v3_2_0_preview2
v3_2_0_preview3
v3_2_0_rc1
```
