### ISSUE TITLE
--link_only flag creates linker errors

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/bake#31]
Test Env:
----------------
OS: Linux (x86_64) 
Bake Version: bake 1.8.0.1
Ruby Version: ruby 2.1.2p95, platform x86_64-linux --

Test Setup:
----------------
1. Execute: Bake Debug -v2 -a black 
    (works properly compiling and linking succeeds.)
2. Execute: Bake Debug -v2 -a black --link_only.
    (Produces various linker errors)

**Comment by aschaal** [comment]
Was a bug in 1.8.0.1. Already fixed. Please update.
