### ISSUE TITLE
generate database for clang based tools

### ISSUE THREAD

**Issue by marcmo** [esrlabs/bake#4]
some tools based on the clang project work with a database that captures build related information.
those can  be generated by build systems (e.g. cmake can do this step with the -DCMAKE_EXPORT_COMPILE_COMMANDS flag, and CMake will take it from there, emitting a compile_commands.json file into your build directory.)

I thinks this database could easily be created using the information available to bake. (see http://clang.llvm.org/docs/JSONCompilationDatabase.html)

## Format

A compilation database is a JSON file, which consist of an array of “command objects”, where each command object specifies one way a translation unit is compiled in the project.

Each command object contains the translation unit’s main file, the working directory of the compile run and the actual compile command.

Example:

    [
      { "directory": "/home/user/llvm/build",
        "command": "/usr/bin/clang++ -Irelative -DSOMEDEF=\"With spaces, quotes and \\-es.\" -c -o file.o file.cc",
        "file": "file.cc" },
      ...
    ]

The contracts for each field in the command object are:
*directory:* The working directory of the compilation. All paths specified in the command or file fields must be either absolute or relative to this directory.
*file:* The main translation unit source processed by this compilation step. This is used by tools as the key into the compilation database. There can be multiple command objects for the same file, for example if the same source file is compiled with different configurations.
*command:* The compile command executed. After JSON unescaping, this must be a valid command to rerun the exact compilation step for the translation unit in the environment the build system uses. Parameters use shell quoting and shell escaping of quotes, with ‘"‘ and ‘\‘ being the only special characters. Shell expansion is not supported.

**Comment by aschaal** [comment]
This is already done. Ask Nico if he is satisfied. Feel free to reopen the issue if there is more todo.

**Comment by marcmo** [comment]
how can I generate the output?
this is what I can do with a recent version:
~~~
 $ bake -h
-- bake 2.10.0, ruby 2.1.3p242, platform x86_64-linux --

Usage: bake [options]
 [-b] <name>              Config name of main project
 -m <dir>                 Directory of main project (default is current directory).
 -p <dir>                 Project to build/clean (default is main project)
 -f <name>                Build/Clean this file only.
 -c                       Clean the file/project.
 -a <scheme>              Use ansi color sequences (console must support it). Possible values are 'white' and 'black'.
 -v<level>                Verbose level from 0 to 3, whereas -v0 is less, -v1 is normal (default) and -v2 and -v3 are more verbose.
 -r                       Stop on first error.
 -w <root>                Add a workspace root (can be used multiple times).
                          If no root is specified, the parent directory of the main project is added automatically.
 --show_configs           Shows all configs with DefaultToolchain.
 --rebuild                Clean before build.
 --clobber                Clean the file/project (same as option -c) AND the bake cache files.
 --prepro                 Stop after preprocessor.
 --link_only              Only link executables - doesn't update objects and archives or start PreSteps and PostSteps.
                          Forces executables to be relinked.
 --docu                   Builds docu instead of compiling sources.
 --lint                   Performs Lint checks instead of compiling sources.
 --lint_min <num>         If number of files in a project is too large for lint to handle, it is possible
                          to specify only a part of the file list to lint (default -1).
 --lint_max <num>         See above (default -1).
 --ignore_cache           Rereads the original meta files - usefull if workspace structure has been changed.
 --threads <num>          Set NUMBER of parallel compiled files (default is 8).
 --socket <num>           Set SOCKET for sending errors, receiving commands, etc. - used by e.g. Eclipse.
 --toolchain_info <name>  Prints default values of a toolchain.
 --toolchain_names        Prints available toolchains.
 --include_filter <name>  Includes steps with this filter name (can be used multiple times).
                          'PRE', 'POST', 'STARTUP' or 'EXIT' includes all according steps.
 --exclude_filter <name>  Excludes steps with this filter name (can be used multiple times).
                          'PRE', 'POST', 'STARTUP' or 'EXIT' excludes all according steps.
 --show_abs_paths         Compiler prints absolute filename paths instead of relative paths.
 --no_autodir             Disable auto completion of paths like in IncludeDir
 --set <key>=<value>      Sets a variable. Overwrites variables defined in Project.metas (can be used multiple times).
 --show_include_paths     Used by IDEs plugins
 --show_incs_and_defs     Used by IDEs plugins
 --conversion_info        Prints infos for an external tool which converts bake configs for other build systems
 --writeCC2J <name>       Writes compiler command into a json file (experimental!)
 --create exe|lib|custom  Creates a project with exe, lib or custom template

 --version                Print version.
 --show_doc               Open documentation in browser
 -h, --help               Print this help.
 --show_license           Print the license.

 --debug                  Print out backtraces in some cases - used only for debugging bake.
~~~

**Comment by aschaal** [comment]
--writeCC2J <name>

**Comment by marcmo** [comment]
thnx
