### ISSUE TITLE
Add some kind of version constraint in Project.meta files

### ISSUE THREAD

**Issue by marcmo** [esrlabs/bake#5]
currently project.meta files do not specify any requirements for the bake version that it needs.
we could add an optional version requirement that bake then can check, making sure it does not operate on files that require a more recent bake version

**Comment by aschaal** [comment]
Fixed with 2.13.0.

**Comment by marcmo** [comment]
Any readme available that gives more detail?

**Comment by aschaal** [comment]
Yes, have a look at RequiredBakeVersion: http://esrlabs.github.io/bake/syntax/project_meta_syntax.html

Note, my plan is to refactor/rewrite the documentation (the content, not the format) next year. Many new things were introduced in the last time, which should be documented in a clean and understandable way.
