### ISSUE TITLE
export relevant source code

### ISSUE THREAD

**Issue by marcmo** [esrlabs/bake#59]
when building a target in a source-tree, usually only a part of the files in the source tree are actually needed to build this configuration (release build does not include unittest code)
it would be handy to tell bake to export a zip file that contains all relevant sources that are needed to execcute a build

**Comment by aschaal** [comment]
This is already possible: --conversion-info.

Example:
bake Debug -p myLib --conversion-info

Pipe the output (info about the library myLib in this specific build context) to a script which can zip the files.

If you like, I can add this script to the "toolkit"  or I can add it to the documentation. Is that okay for you?

**Comment by marcmo** [comment]
perfect! awesome...working with bake is just soooo good!

**Comment by marcmo** [comment]
yeah...works great!
