### ISSUE TITLE
Eclipse Console background color problem

### ISSUE THREAD

**Issue by fraukeBL** [esrlabs/bake#60]
When starting Eclipse (Version: Mars.1 (4.5.1)) and build with bake (bake 2.11.1) the background color of the console is black as adjusted. If I click in the console window the background color changes to white and the font is not readable anymore.

**Comment by aschaal** [comment]
I tried to reproduce that with different versions, but it has always worked on my machine. You are the only one until now who had this problem...

I have no listener/event or anything else when clicking in the console window. However, it might be possible that another other plugins does this. Or an Eclipse bug in your specific version...

Can you please try to install another standard Eclipse version (in parallel) and try it again? Thank you.

For now I close this. Feel free to reopen if it still occurs. Or contact me directly...
