### ISSUE TITLE
add a run subcommand

### ISSUE THREAD

**Issue by marcmo** [esrlabs/bake#7]
for executable configurations it makes sense to say `bake run --configname` or s.th. like that

workaround currently:
~~~ .ruby
ExecutableConfig Unitest {....}

CustomConfig run {
Dependency config: Unittest
CommandLine "..."
}
~~~

**Comment by aschaal** [comment]
Or just "--run" on the command line.

**Comment by aschaal** [comment]
The generic way is:

```Shell
Project {
  ExecutableConfig Unittest {
    Files "main.cpp"
    DefaultToolchain GCC
    PostSteps {
	  ComandLine "$(OutputDir)/$(ArtifactName) --additionalArgs", filter: run, default: off
    }
  }
}
```

In the shell:
```Shell
bake Unittest --include_filter run
```

--> Issue closed.

**Comment by Nicoretti** [comment]
I hope you reconsider this, to me the mentioned way seems somewhat more complicate and inconvineint.
 
1. I have to adjust the Project.meta (If it is an executable config => bake knows that it can be executed)
2. More to type 
3. included_filter seems  and feels to me to be a workaround

IMHO:
`bake  [target] --run`
would be nice to have

**Comment by aschaal** [comment]
Not really.
What you can do to avoid changes in Project.meta is:
```shell
bake Unittest && bin_blah/app.exe
```

Reasons for doing this in bake:
- You have several command line args for the executable
- You could have several executables in the dependencies. Even ExecutableConfigs can depend on ExecutableConfigs, so you have to decide which executables to run. If you say only top level then you have a problem for wrapper configs to e.g. get licenses, preparing workspaces, etc...
- Shall bake do the previous steps (like compiling) or ONLY run the executable? This is not obvious. If you want to run only the executable, bake has still to analyze the workspace, which might take a short time for large workspaces. If you want to do the previous steps, than you have the behaviour of --include_filter.

An additional run-function would make bake more (a little bit) more complex, with low benefit...

However, I will rethink the bake args, see #51.
--include_filter should be --include-filter or maybe just --do:
```shell
bake Unittest --do run
```
