### ISSUE TITLE
Support for multiple inheritance for Configs

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#70]
Sometimes code duplication in Bake configuration could be avoided by multiple inheritance.
Consider the case where a **two** targets shall be build with **two** toolchain setups, but some parameters (e.g. file list) shall only be (partially) defined only once and extended in the specializations.

Possible syntax for the Project.meta could look like this:

``
ExecutableConfig Foo, extends: "Bar, Baz" {
  }
``

There is a known workaround with the "adapt" feature. The drawback of this solution is that the information needs to be passed via commandline argument and cannot be stored in the Project.meta.

This feature is already discussed with Alex and this ticket is just reminder.

**Comment by aschaal** [comment]
Fixed in 2.15.0.
