### ISSUE TITLE
Provide project/build information in an easy to use format

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/bake#73]
Bake supports several mechanisms to extract compile/build settings bake is using to build a project/target. 

e.g.:
 * --incs-and-defs
 * --conversion-info
 * --writeCC2J

```javascript

{
   "Project1": { 
                        "includes" : ["includepath/one", "includepath/two", ...],  
                         "cpp_defines": ["GTEST_USE_OWN_TR1_TUPLE=1", "UNIT_TEST"],
                         "c_defines": ["DEF", ...],
                         "asm_defines": ["DEF1", ...]
                      },
}

```
Please provide one generic mechanism which can be used to extract all of this information
in a manner thats easy to use by other tools or tool developers. 
E.g. json, yaml so tool developers can focus on writing tools and not parsers for yet another custom format. :P

**Comment by aschaal** [comment]
Added: --incs-and-defs=json
