### ISSUE TITLE
ExecutableConfigs artifacts have .exe suffix by default

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#79]
The .exe suffix for binaries by default should only be appended on Windows platforms.
Sure - with ArtifactName this can be overwritten, but this foo.exe files on OSX/Linux really hurt.

**Comment by gizmomogwai** [comment]
do you really dislike the .exe ? sure .. it does hurt when typed out ...
but libblub.so is even worse :)

**Comment by aschaal** [comment]
Done in 2.24.0.
