### ISSUE TITLE
cannot interrupt build with Ctrl-C

### ISSUE THREAD

**Issue by marcmo** [esrlabs/bake#8]

**Comment by marcmo** [comment]
example: build project with 100s of subprojects => Ctrl-C apparently only interrupts one thread
tested under Linux

**Comment by marcmo** [comment]
bake --version
-- bake 2.9.2, ruby 2.1.3p242, platform x86_64-linux --

**Comment by aschaal** [comment]
Fixed. Problem was that SIGINT was not trapped under Linux. CTRL-C behaves differently in Windows and Linux.
In Windows all (sub)processes are killed, in Linux an Interrupt Exception is raised.
Now bake waits for all (sub)processes to terminate and (this is new for Linux) does not start to compile another project.

**Comment by marcmo** [comment]
thanks for the fix!
