### ISSUE TITLE
Can't remove build artifacts with built in bake -c flag.

### ISSUE THREAD

**Issue by Nicoretti** [esrlabs/bake#87]
Due to the fact that the Executable config (Project Master) is responsible for build settings and cleaning up, build artifacts can't be deleted as soon as the Master Project is deleted.

Example: 
Project A depends on Project B with config lib.

Bake creates in source build in Project A and Project B, but it should build all artifacts in Project A.
Why?
If I get rid of Project A but still need Project B because of other Projects I won't be able using the
built in clean mechanism of bake to throw away the build Artifacts created by the build of Project A.

The Project who is master should keep the Artifacts because it will be used for cleanup!

**Comment by aschaal** [comment]
This cannot be solved completely. You can configure a special output folder for you projects (e.g. in DefaultToolchain with Variables including ProjectName and ProjectConfig).
However, I have created a "bakeclean" script. Write "bakeclean --help" for more information.
