### ISSUE TITLE
Support ccache as a addon for some toolchains

### ISSUE THREAD

**Issue by flxo** [esrlabs/bake#90]
[ccache](https://ccache.samba.org/) is a nice performance boost. Right now ccache together with bake is just overwriting the command of a toolchain e.g:

```
DefaultToolchain GCC {
    Compiler CPP, command: "ccache g++" {
...
```

A more sophisticated variant would be, to be able to enable/disable it via some kind of switch. The use case for this is when a CI build does not want to make use of ccache - but developers want.
The Android build system approach is to use ccache when "USE_CACHE" is set in the environment. This could be one way, but probably bake want to use the adopt feature...

**Comment by aschaal** [comment]
Fixed with 2.31.0, see "prefix" attribute of Compiler definition in (Default)Toolchain.
